stages:
  - test
  - build
  - deploy

variables:
  APP_VERSION: $CI_COMMIT_TAG

run_tests:
  image: node:12.16.3
  stage: test
  
  script:
    - npm i
    - npm run test:unit


build_tag_image:
  image: docker:19.03.1
  stage: build
  services:
    - docker:19.03.1-dind
  environment:
    name: prod
  only:
    - tags

  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"

  before_script:
    - echo "VUE_APP_API_URL=$VUE_APP_API_URL" > .env
    - echo "VUE_APP_HTTP_AUTHORIZATION_HEADER=$VUE_APP_HTTP_AUTHORIZATION_HEADER" >> .env
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_DOCKER_REGISTRY
    - docker build --build-arg VERSION=$APP_VERSION --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY_IMAGE:latest

deploy_prod:
  image: registry.gitlab.com/pablo-moreno/builder
  stage: deploy
  environment:
    name: prod
  needs:
    - build_tag_image
  only:
    - tags
  when: manual
  script:
    - wget --post-data "" $CD_WEBHOOK
    - touch /tmp/success
